version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  node-backend:
    image: node:latest
    container_name: node-backend
    build:
      context: ./backend
    ports:
      - "80:3001"
    depends_on:
      - mongodb
    networks:
      - backend
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/livre

volumes:
  mongo-data:

networks:
  backend:
