name: CI/CD Pipeline for Render

on:
  push:
    branches:
      - main  # Déclenche ce pipeline pour chaque push vers la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # L'environnement où le workflow s'exécutera

    steps:
    # Étape 1: Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2: Configurer Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Étape 3: Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t render-app .

    # Étape 4: Authentification auprès de Render
    - name: Render Login
      run: |
        echo "Rendering API Key: ${{ secrets.RENDER_API_KEY }}"
        curl -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
             -X POST \
             -d '{"service":"livre","branch":"main","docker":"true"}' \
             https://livre-u2u0.onrender.com

    # Étape 5: Pousser l'image Docker vers Render
    - name: Push Docker image to Render
      run: |
        docker tag render-app registry.render.com/Nambinina I. DIMBY/livre:latest
        docker push registry.render.com/Nambinina I. DIMBY/livre:latest
