name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

# Définir les jobs de CI/CD
jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Étape 2 : Installer Docker et Docker Compose
      - name: Set up Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Installer Docker Compose

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose services
        run: docker-compose -f docker-compose.yml up -d



